apiVersion: v1
kind: Service
metadata:
  name: kubearmor-mysql
  labels:
    kubearmor-app: kubearmor-mysql
spec:
  selector:
    kubearmor-app: kubearmor-mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-mysql
  labels:
    kubearmor-app: kubearmor-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-mysql
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-mysql
      annotations:
        kubearmor-policy: audited
    spec:
      containers:
      - name: kubearmor-mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root-passwd
        - name: MYSQL_DATABASE
          value: kubearmor-db
        - name: MYSQL_USER
          value: kubearmor
        - name: MYSQL_PASSWORD
          value: kubearmor-passwd
        ports:
        - name: mysql-port
          containerPort: 3306
